### ISSUE TITLE
Figure sizes

### ISSUE THREAD

**Issue by pedro9589** [Deep-Learning-IGP-TUBS-SoSe2023/Deep-Learning-IGP-TUBS-SoSe2023.github.io#1]
@rlettmoden, please, check the size of the figures: Figure 1 could be bigger, Figure 2 should be smaller, and Figures 3 and 4 (results) should be bigger. Also, you can add more results if available.

**Comment by pedro9589** [comment]
You can use html to change the size of the figures:

`<img src="drawing.jpg" alt="drawing" style="width:200px;"/>`

**Comment by rlettmoden** [comment]
For the detailed results, I would prefer to refer to our paper. But added a tensorboard plot of the advantages of augmentations for more visualizations
